apiVersion: v1
kind: Service
metadata:
  name: myweb-svc
  labels:
    app: myweb
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8085
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: myweb

