apiVersion: v1
kind: Service
metadata:
  name: myweb-svc
  labels:
    app: myweb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8085
  - port: 443
    protocol: TCP
    targetPort: 8443
 type: LoadBalancer
  selector:
    app: myweb
