apiVersion: v1
kind: Service
metadata:
  name: myweb-svc
  labels:
    app: myweb
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8085
    targetPort: 80
  - name: https
    port: 9443
    protocol: TCP
    targetPort: 80
  selector:
    app: myweb

