apiVersion: v1
kind: Service
metadata:
 name: myweb-svc
 labels:
   app: myweb
spec:
  clusterIP:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
 selector:
   app.kubernetes.io/name: myweb
