apiVersion: v1
kind: Service
metadata:
 name: myweb-svc
 labels:
   app: myweb
spec:
 type: NodePort
 ports:
 - ports: 80
   nodePort: 30080
   protocol: TCP
 selector:
   app.kubernetes.io/name: myweb
