name: Docker Image CI
on:
  push:
    paths-ignore:
      - 'myweb-app'
    branches:
      - 'main'
jobs:

  build:

    runs-on: for-kuberentes

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mavweb:$(date +%s)
