name: ci

on:
  push:
    paths-ignore:
      - 'myweb-app'
    branches:
      - 'main'
env:
  git_hash: ${{ github.sha }}    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: https://github.com/matymav/myweb.git#main
          push: true
          tags: matymav/matyweb:latest

      - name: Update image tag for container myweb in deploy.yaml
        uses: loveholidays/gitops-action-yaml-updater@v1.0
        with:
          mode: IMAGE_TAG
          container-name: myweb
          new-image-tag: ${{ env.git_hash }}
          files: myweb-app/deploy.yaml
