name: Edit Files

on:
  push:
    paths-ignore:
      - 'myweb-app'
    branches:
      - 'main'

env:
  git_hash: ${{ github.sha }} 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Edit Files
      uses: TaiStudio/action-edit-YML@main
      with:
        type: 'single'
        files: "./myweb-app/deploy.yaml"
        elementSTR: "['spec'][0]['template'][0]['spec'][0]['containers'][0]['image']"
        replace: "matymav/matyweb:latest"
        replaceFor: "matymav/matyweb:${{ env.git_hash }}"
